### ISSUE TITLE
Support for vendored OpenSSL

### ISSUE THREAD

**Issue by mkpankov** [sfackler/hyper-openssl#33]
I want to use vendored OpenSSL. There's a feature `vendored` in `rust-openssl`, but it's not supported upwards

**Comment by sfackler** [comment]
```toml
[dependencies]
hyper-openssl = "0.9"
openssl = { version = "0.10", features = ["vendored"] }
```
